### ISSUE TITLE
How cross compile OpenCV for Android?

### ISSUE THREAD

**Issue by EdgeAI-Lab** [MRYangY/opencv-contrib-lib4Android#1]
**Hello!**
**I use Android NDK18  & opencv/platform/android/build_sdk.py   to cross-compile opencv, but it has many errors, Can you help me?**
**Thanks!**

**Comment by MRYangY** [comment]
@FanHongchuang 你的ndk version 有点高啊,你可以看看这篇文章 https://blog.csdn.net/qq_34902522/article/details/81533145

**Comment by EdgeAI-Lab** [comment]
@MRYangY 现在已经可以正确编译了，谢谢指教！
